server {
    # SABOTAGE 2: I removed the semicolon at the end of this line. 
    # Nginx is incredibly strict about syntax.
    listen 80

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}